project:
  type: website
  output-dir: docs

website:
  title: "Datacasual"
  site-url: https://datacasual.com/
  description: "Tales of an accidental data scientist"
  google-analytics: "UA-163988972-1"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - text: "![](posts/images/bsky.svg){width=16}"
        href: https://bsky.app/profile/doctormiko.bsky.social
      - icon: github
        href: https://github.com/micbucci
      - icon: twitter
        href: https://twitter.com/mikonapoli

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css




