project:
  type: website
  output-dir: docs

website:
  title: "Datacasual - Tales of an accidental data scientist"
  navbar:
    right:
      - about.qmd
      - text: "![](posts/images/bsky.svg){width=16}"
        href: https://bsky.app/profile/doctormiko.bsky.social
      - icon: github
        href: https://github.com/micbucci
      - icon: twitter
        href: https://twitter.com/mikonapoli

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css




